title: Muhammad Riyan Athariq
email: riiyanathrq@gmail.com
description: >-
  Software Engineer | Backend Engineer | Golang | API | Cloud
url: "https://github.com/riyanathariq/portofolio"

logo: ./assets/profpic_circ.png
markdown: kramdown
