title: Muhammad Riyan Athariq
email: riiyanathrq@gmail.com
description: >-
  Software Engineer | Backend Engineer | Golang | API | Cloud
url: "https://github.com/riyanathariq/portofolio"

theme: jekyll-theme-minimal
logo: ./assets/profpic_circ.png
